# Generated by Django 4.1 on 2024-04-10 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categories_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='chats',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.IntegerField(max_length=225)),
                ('sender_type', models.CharField(max_length=225)),
                ('receiver', models.IntegerField(max_length=225)),
                ('reciver_type', models.CharField(max_length=225)),
                ('message', models.CharField(max_length=225)),
                ('date_time', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='DrivingRequest',
            fields=[
                ('driving_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driving_school_app.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Drivingschool',
            fields=[
                ('drivingschool_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('license', models.CharField(max_length=1500)),
                ('Latitude', models.CharField(default='000', max_length=225)),
                ('Longitude', models.CharField(default='000', max_length=225)),
                ('Cat', models.CharField(default='twowheeler', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('usertype', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('trainer_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('drivingschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driving_school_app.drivingschool')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driving_school_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('dob', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('Drivingschool', models.ForeignKey(default='000', on_delete=django.db.models.deletion.CASCADE, to='driving_school_app.drivingschool')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driving_school_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('tutorial_id', models.AutoField(primary_key=True, serialize=False)),
                ('tutorial', models.FileField(upload_to='')),
                ('type', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driving_school_app.trainer')),
            ],
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('queries_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=150)),
                ('reply', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('drivingschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driving_school_app.drivingschool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driving_school_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150)),
                ('amount', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driving_school_app.drivingrequest')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseRequest',
            fields=[
                ('license_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driving_school_app.categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driving_school_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='drivingschool',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driving_school_app.login'),
        ),
        migrations.AddField(
            model_name='drivingrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driving_school_app.user'),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=150)),
                ('reply_text', models.CharField(max_length=150)),
                ('date', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driving_school_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedTrainer',
            fields=[
                ('assigned_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer', to='driving_school_app.trainer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee', to='driving_school_app.user')),
            ],
        ),
    ]
